version: "3.8"

services:
  netapp-storage-service:
    build: .
    image: netapp-storage-service:local
    container_name: netapp-storage-service
    ports:
      - "8080:8080"
    networks:
      - netapp-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - netapp-net
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - netapp-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  netapp-net:
    driver: bridge
