apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed
  labels:
    app: distributed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: distributed
  template:
    metadata:
      labels:
        app: distributed
    spec:
      containers:
        - name: distributed
          image: your-dockerhub-username/distributed:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
